DROP TABLE mailing CASCADE;
CREATE TABLE IF NOT EXISTS mailing (
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(80) NOT NULL,
    CONSTRAINT mailing_pk PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);